In [3]:
import pandas as pd
d = {
    "name":["vishal","vineet","virat"],      #3rows
    "salary":[100,200,300]                  #3rows
}
df=pd.DataFrame(data=d)
df["holidays"] = df["salary"] / 100
df["increment"] = [10,20,30]
#delete column
df.drop(["salary","name"],axis=1)
df

     name  salary  holidays  increment
0  vishal     100       1.0         10
1  vineet     200       2.0         20
2   virat     300       3.0         30

In [4]:
import pandas as pd
d = {
    "name":["vishal","vineet","virat"],      #3rows
    "salary":[100,200,300]                  #3rows
}
df=pd.DataFrame(data=d)
df["holidays"] = df["salary"] / 100
df["increment"] = [10,20,30]
#delete column
df.drop(["salary","name"],axis=1,inplace=True)
df

   holidays  increment
0       1.0         10
1       2.0         20
2       3.0         30

In [6]:
import pandas as pd
d = {
    "name":["vishal","vineet","virat"],      #3rows
    "salary":[100,200,300]                  #3rows
}
df=pd.DataFrame(data=d)
df

     name  salary
0  vishal     100
1  vineet     200
2   virat     300

In [8]:
df.loc[2,"name"]
df.iloc[2,0]

'virat'

In [11]:
# get single row data
df.iloc[1]

name      vineet
salary       200
Name: 1, dtype: object

In [16]:
#get single row using loc
df.loc[1]

name      vineet
salary       200
Name: 1, dtype: object

In [17]:
#get multi rows using iloc
df.iloc[0:3]

     name  salary
0  vishal     100
1  vineet     200
2   virat     300

In [18]:
#get multi rows using loc
df.loc[0:3]

     name  salary
0  vishal     100
1  vineet     200
2   virat     300

In [22]:
#to get sub data
df1 = df.iloc[0:2,[0]] # ->o,1 and cols ->0 |name
df1

     name
0  vishal
1  vineet

In [34]:
#to get sub data using loc
df1 = df.loc[0:1,["salary"]]
df1

   salary
0     100
1     200

In [43]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)
df.loc[1,"Name"]

'Riya'

In [48]:
df.iloc[0:2,[2]]

  Department
0         IT
1         HR

In [49]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [50]:
df.iloc[5,0]

'priya'

In [60]:
df.iloc[5:7,[0,1]]

     name  gender
5   priya  Female
6  Sundar    Male

In [52]:
df.loc[13,"name"]

'Jenifer'

In [58]:
df.loc[12:13,["name","gender"]]

       name  gender
12  Murugan    Male
13  Jenifer  Female

In [62]:
df.iloc[3:9,[0]]

      name
3     raja
4     usha
5    priya
6   Sundar
7  Kavitha
8   Dinesh

In [64]:
df.iloc[3:9:5] #ratio 5 is used to jump

     name gender  physics  maths  english
3    raja   Male       30     25       40
8  Dinesh   Male       56     45       67

In [65]:
#filter1
df[df["english"] == 95]

     name gender  physics  maths  english
1  rajesh   Male       96    100       95

In [66]:
#filter2
df[df["maths"] < 60]

      name  gender  physics  maths  english
3     raja    Male       30     25       40
4     usha  Female       67     45       78
5    priya  Female       56     46       78
8   Dinesh    Male       56     45       67
11     Ram    Male       78     55       47

In [67]:
#physics values less than and equal to 56
df[df["physics"] <= 56]

       name  gender  physics  maths  english
3      raja    Male       30     25       40
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
12  Murugan    Male       34     89       78

In [71]:
#maths 90 above and english 90 above
# df[(condition1)&(condition2)]
df[(df["maths"] > 90)&(df["english"] > 90)]

      name  gender  physics  maths  english
1   rajesh    Male       96    100       95
10   Gowri  Female      100    100      100