In [5]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [11]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
#by default ascending
df.sort_values("english")

       name  gender  physics  maths  english
9      Hema  Female       71     90       23
3      raja    Male       30     25       40
11      Ram    Male       78     55       47
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
2   moorthy    Male       89     90       70
5     priya  Female       56     46       78
0      arun    Male       88     87       78
4      usha  Female       67     45       78
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
1    rajesh    Male       96    100       95
10    Gowri  Female      100    100      100

In [12]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
# for descending
df.sort_values("english",ascending=False)

       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
1    rajesh    Male       96    100       95
13  Jenifer  Female       67     88       90
4      usha  Female       67     45       78
5     priya  Female       56     46       78
0      arun    Male       88     87       78
12  Murugan    Male       34     89       78
2   moorthy    Male       89     90       70
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
11      Ram    Male       78     55       47
3      raja    Male       30     25       40
9      Hema  Female       71     90       23

In [14]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
#multiple columns sort
df.sort_values(["english","maths"],ascending=[False,True])

       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
1    rajesh    Male       96    100       95
13  Jenifer  Female       67     88       90
4      usha  Female       67     45       78
5     priya  Female       56     46       78
0      arun    Male       88     87       78
12  Murugan    Male       34     89       78
2   moorthy    Male       89     90       70
8    Dinesh    Male       56     45       67
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
11      Ram    Male       78     55       47
3      raja    Male       30     25       40
9      Hema  Female       71     90       23

In [15]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
#sorting by name
df.sort_values("name") # it is done according to ascii values

       name  gender  physics  maths  english
8    Dinesh    Male       56     45       67
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
13  Jenifer  Female       67     88       90
7   Kavitha  Female       78     71       67
12  Murugan    Male       34     89       78
11      Ram    Male       78     55       47
6    Sundar    Male       12     67       67
0      arun    Male       88     87       78
2   moorthy    Male       89     90       70
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
4      usha  Female       67     45       78

In [16]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
# a to z
df["name"] = df["name"].str.upper()
df1=df.sort_values(by=["name"])
print(df1)

       name  gender  physics  maths  english
0      ARUN    Male       88     87       78
8    DINESH    Male       56     45       67
10    GOWRI  Female      100    100      100
9      HEMA  Female       71     90       23
13  JENIFER  Female       67     88       90
7   KAVITHA  Female       78     71       67
2   MOORTHY    Male       89     90       70
12  MURUGAN    Male       34     89       78
5     PRIYA  Female       56     46       78
3      RAJA    Male       30     25       40
1    RAJESH    Male       96    100       95
11      RAM    Male       78     55       47
6    SUNDAR    Male       12     67       67
4      USHA  Female       67     45       78

In [29]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
# add column total = phy+math+eng+hindi
df["total"] = df["physics"]+df["maths"]+df["english"]
df

       name  gender  physics  maths  english  total
0      arun    Male       88     87       78    253
1    rajesh    Male       96    100       95    291
2   moorthy    Male       89     90       70    249
3      raja    Male       30     25       40     95
4      usha  Female       67     45       78    190
5     priya  Female       56     46       78    180
6    Sundar    Male       12     67       67    146
7   Kavitha  Female       78     71       67    216
8    Dinesh    Male       56     45       67    168
9      Hema  Female       71     90       23    184
10    Gowri  Female      100    100      100    300
11      Ram    Male       78     55       47    180
12  Murugan    Male       34     89       78    201
13  Jenifer  Female       67     88       90    245

In [30]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
# add row
df.loc[14] = ["yash","male",50,30,90]
df
df["total"] = df["physics"]+df["maths"]+df["english"]
df

       name  gender  physics  maths  english  total
0      arun    Male       88     87       78    253
1    rajesh    Male       96    100       95    291
2   moorthy    Male       89     90       70    249
3      raja    Male       30     25       40     95
4      usha  Female       67     45       78    190
5     priya  Female       56     46       78    180
6    Sundar    Male       12     67       67    146
7   Kavitha  Female       78     71       67    216
8    Dinesh    Male       56     45       67    168
9      Hema  Female       71     90       23    184
10    Gowri  Female      100    100      100    300
11      Ram    Male       78     55       47    180
12  Murugan    Male       34     89       78    201
13  Jenifer  Female       67     88       90    245
14     yash    male       50     30       90    170

In [42]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
# delete row and delete column
df_N = df.drop(index = 13).drop(columns = ["english"])
df_N

       name  gender  physics  maths
0      arun    Male       88     87
1    rajesh    Male       96    100
2   moorthy    Male       89     90
3      raja    Male       30     25
4      usha  Female       67     45
5     priya  Female       56     46
6    Sundar    Male       12     67
7   Kavitha  Female       78     71
8    Dinesh    Male       56     45
9      Hema  Female       71     90
10    Gowri  Female      100    100
11      Ram    Male       78     55
12  Murugan    Male       34     89

In [43]:
import pandas as pd
dict = [
    {
      "name":"arun","gender":"Male","physics":88,"maths":87,"english":78
   },
    {"name":"rajesh","gender":"Male","physics":96,"maths":100,"english":95},
    {"name":"moorthy","gender":"Male","physics":89,"maths":90,"english":70},
    {"name":"raja","gender":"Male","physics":30,"maths":25,"english":40},
    {"name":"usha","gender":"Female","physics":67,"maths":45,"english":78},
    {"name":"priya","gender":"Female","physics":56,"maths":46,"english":78},
    {"name":"Sundar","gender":"Male","physics":12,"maths":67,"english":67},
    {"name":"Kavitha","gender":"Female","physics":78,"maths":71,"english":67},
    {"name":"Dinesh","gender":"Male","physics":56,"maths":45,"english":67},
    {"name":"Hema","gender":"Female","physics":71,"maths":90,"english":23},
    {"name":"Gowri","gender":"Female","physics":100,"maths":100,"english":100},
    {"name":"Ram","gender":"Male","physics":78,"maths":55,"english":47},
    {"name":"Murugan","gender":"Male","physics":34,"maths":89,"english":78},
    {"name":"Jenifer","gender":"Female","physics":67,"maths":88,"english":90}
]
df = pd.DataFrame(dict)
#delete data from index no.6 to 13
df_N = df.drop(index = [6,7,8,9,10,11,12,13])
df_N

      name  gender  physics  maths  english
0     arun    Male       88     87       78
1   rajesh    Male       96    100       95
2  moorthy    Male       89     90       70
3     raja    Male       30     25       40
4     usha  Female       67     45       78
5    priya  Female       56     46       78

In [63]:
#delete data from index no. 6 to 13
df.drop(df.index[6:15] , inplace = True)
print(df)
#add new column
df["date_of_join"] = ["2025-12-03","2025-03-30","2026-01-04","2025-12-09","2024-08-03","2025-11-03"]
print('\n')
print(df["date_of_join"].dtype)

print('\n')
#converting datatype
print("----------After Conversion Of DataType----------")
df["date_of_join"] = pd.to_datetime(df["date_of_join"])
print(df)
print('\n')
print(df["date_of_join"].dtype)
print('\n')

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3