In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
df.isnull()

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

    name  roll no  marks
0  False    False  False
1  False    False  False
2  False    False  False
3  False    False  False
4  False    False  False

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
#-> anjali's only marks should be null
df.loc[4]

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

name        anjali
roll no    1234567
marks           50
Name: 4, dtype: object

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
#-> anjali marks should be done
df.loc[4,"marks"] = "null"
df.loc[4]

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

/tmp/ipykernel_1450/853810119.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'null' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[4,"marks"] = "null"

name        anjali
roll no    1234567
marks         null
Name: 4, dtype: object

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
#-> anjali marks should be done
df.loc[4,"marks"] = None
df.isnull()

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

    name  roll no  marks
0  False    False  False
1  False    False  False
2  False    False  False
3  False    False  False
4  False    False   True

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
#-> anjali marks should be done
df.loc[4,"marks"] = None
df.loc[4]
#-> for column count missing values
df.isnull().sum()

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

name       0
roll no    0
marks      1
dtype: int64

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)

       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   50.0

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
# to remove nulll values
df.dropna()

       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   50.0

       name  roll no  marks
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   50.0

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
# to remove of column with null values
print(df.dropna(axis=1))

       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   50.0
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

In [82]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
# to replace nan with a values
df.fillna(100)

       name  roll no  marks
0   dheeraj      NaN    NaN
1     kunal      NaN   20.0
2  abhishek      NaN   30.0
3   praveen      NaN   40.0
4    anjali      NaN   50.0

       name  roll no  marks
0   dheeraj    100.0  100.0
1     kunal    100.0   20.0
2  abhishek    100.0   30.0
3   praveen    100.0   40.0
4    anjali    100.0   50.0

In [86]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
df["roll no"].fillna(200)

       name  roll no  marks
0   dheeraj      NaN    NaN
1     kunal      NaN   20.0
2  abhishek      NaN   30.0
3   praveen      NaN   40.0
4    anjali      NaN   50.0

0    200.0
1    200.0
2    200.0
3    200.0
4    200.0
Name: roll no, dtype: float64

In [90]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
#marks -> mean | nan fill with average
mean = df["marks"].mean()
df["marks"] = df["marks"].fillna(mean)
df

       name  roll no  marks
0   dheeraj      NaN   35.0
1     kunal      NaN   20.0
2  abhishek      NaN   30.0
3   praveen      NaN   40.0
4    anjali      NaN   50.0

In [103]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
#manually
df["marks"].sum()

df["marks"].max()

df["marks"].min()

df["marks"].mean()

np.float64(35.0)

In [108]:
#concatenate
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
df1=pd.read_json(url)
pd.concat([df,df1])

       name  roll no  marks
0   dheeraj      NaN    NaN
1     kunal      NaN   20.0
2  abhishek      NaN   30.0
3   praveen      NaN   40.0
4    anjali      NaN   50.0
0   dheeraj      NaN    NaN
1     kunal      NaN   20.0
2  abhishek      NaN   30.0
3   praveen      NaN   40.0
4    anjali      NaN   50.0

In [109]:
#concatenate
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
df1=pd.read_json(url)
pd.concat([df,df1],axis=1)

       name  roll no  marks      name  roll no  marks
0   dheeraj      NaN    NaN   dheeraj      NaN    NaN
1     kunal      NaN   20.0     kunal      NaN   20.0
2  abhishek      NaN   30.0  abhishek      NaN   30.0
3   praveen      NaN   40.0   praveen      NaN   40.0
4    anjali      NaN   50.0    anjali      NaN   50.0

In [122]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
print("----------Main Data----------")
print(df)
df1 = pd.read_json(url)
print("____________________________________")
print('\n')
#concatanation(by default --> row)
print("----------Cancatanation By row----------")
print(pd.concat([df,df1]))
#concatanation (by column)
print('\n')
print("----------Cancatanation By Column----------")
df2=pd.concat([df,df1],axis=1)
print(df2)
#change the name of abhishek
print('\n')
print("----------Changing Name----------")
df2.loc[2,"name"] = "yash"
print(df2)

----------Main Data----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN
____________________________________


----------Cancatanation By row----------
       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567    NaN


----------Cancatanation By Column----------
       name  roll no  marks      name  roll no  marks
0   dheeraj      123    NaN   dheeraj      123    NaN
1     kunal     1234   20.0     kunal     1234   20.0
2  abhishek    12345   30.0  abhishek    12345   30.0
3   praveen    12356   40.0   praveen    12356   40.0
4    anjali  1234567    NaN    anjali  1234567    NaN


----------Changing Name----------
      name  roll no  marks     name  roll no  marks
0  dheeraj      123    NaN  dheeraj      123    NaN
1    kunal     1234   20.0    kunal     1234   20.0
2     yash    12345   30.0     yash    12345   30.0
3  praveen    12356   40.0  praveen    12356   40.0
4   anjali  1234567    NaN   anjali  1234567    NaN

In [124]:
import pandas as pd
url = "https://raw.githubusercontent.com/kunaldhabhai25-ctrl/Data-Science__45-Days/main/file2.json"
df= pd.read_json(url)
#change name of ab abhishek by yash
df1.loc[2,"name"] = "yash"
print(df1)

      name  roll no  marks
0  dheeraj      123    NaN
1    kunal     1234   20.0
2     yash    12345   30.0
3  praveen    12356   40.0
4   anjali  1234567    NaN