In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
df.isnull()

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

    name  roll no  marks
0  False    False  False
1  False    False  False
2  False    False  False
3  False    False  False
4  False    False  False

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
#-> anjali's only marks should be null
df.loc[4]

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

name        anjali
roll no    1234567
marks           50
Name: 4, dtype: object

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
#-> anjali marks should be done
df.loc[4,"marks"] = "null"
df.loc[4]

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

/tmp/ipykernel_1450/853810119.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'null' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[4,"marks"] = "null"

name        anjali
roll no    1234567
marks         null
Name: 4, dtype: object

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
#-> anjali marks should be done
df.loc[4,"marks"] = None
df.isnull()

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

    name  roll no  marks
0  False    False  False
1  False    False  False
2  False    False  False
3  False    False  False
4  False    False   True

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
#-> anjali marks should be done
df.loc[4,"marks"] = None
df.loc[4]
#-> for column count missing values
df.isnull().sum()

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

name       0
roll no    0
marks      1
dtype: int64

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)

       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   50.0

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
# to remove nulll values
df.dropna()

       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   50.0

       name  roll no  marks
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   50.0

In [ ]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
# to remove of column with null values
print(df.dropna(axis=1))

       name  roll no  marks
0   dheeraj      123    NaN
1     kunal     1234   20.0
2  abhishek    12345   30.0
3   praveen    12356   40.0
4    anjali  1234567   50.0
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

In [80]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)
# to replace nan with a values
df.fillna(100)

ValueError: Unexpected character found when decoding object value

In [78]:
import pandas as pd
url =  "https://raw.githubusercontent.com/yashmourya236-code/Data_Science_-45-Days-/main/file2.json"
df=pd.read_json(url)
print(df)

ValueError: Unexpected character found when decoding object value